// @ts-ignore
import { expect, test } from "bun:test";
import { reduceDescriptions } from "./playlistUtils";

test("playlist:reduceDescriptions", () => {
  const o = [
    '1. ［cover］Eternal Lullaby',
    "2. eAeon Don't (Feat. RM) Lyrics (이이언 그러지 마 (Feat. RM) 가사) [Color Coded Lyrics/Han/Rom/Eng]",
    '3. [가사] 이이언, 바이바이 나의 아이 / 다시 돌아오지 않을 나의 밤 너의 마음 (eAeon - Bye Bye)',
    '4. AKMU IU NAKKA Lyrics (악동뮤지션 아이유 낙하 가사) [Color Coded Lyrics/Han/Rom/Eng]',
    "5. AKMU 악뮤 (with 이선희) - 'BATTLEFIELD (전쟁터)' LYRICS COLOR CODED [HAN/ROM/ENG]",
    '6. Full Confession',
    '7. Night of the Living You',
    '8. Sleeping At Last - "Saturn" (Official Music Video)',
    '9. 브레이브걸스 치맛바람 가사 (Brave Girls Chi Mat Ba Ram Lyrics) [Color Coded Lyrics/Han/Rom/Eng]',
    '10. Nox (밤의 정원)',
    '11. Forest (수피 樹皮)',
    '12. 결(KYUL) - 아픔이 아문 건지 Feel Better',
    '13. Someone You Used To Know',
    '14. 2PM (투피엠) - A.D.T.O.Y. (하.니.뿐.) [Colour Coded Lyrics/Han/Rom/Eng]',
    '15. Doja Cat - Kiss Me More (Lyrics) ft. SZA',
    '16. Bruno Mars, Anderson .Paak - Leave The Door Open (Lyrics)',
    '17. 날 뱀같은 년이라며: Taylor Swift - You Need To Calm Down (2019) [가사해석]',
    '18. AJ Mitchell - Stop (Official Visualizer)',
    '19. Josef Salvat - melt',
    '20. King - Foreign Figures (LYRICS)',
    '21. Kana Nishino  - If  (Lyrics)',
    '22. CheerS',
    '23. TWICE Alcohol-Free Lyrics (트와이스 Alcohol-Free 가사) [Color Coded Lyrics/Han/Rom/Eng]',
    '24. TAEMIN Advice Lyrics (태민 Advice 가사) (Color Coded Lyrics)',
    '25. Block B (블락비) - Toy - (Color Coded Han|Rom|Eng Lyrics) | by Yankat',
    '26. FANCY',
    '27. HANN (Alone) (한(一))',
    '28. HYOLYN (효린), CHANGMO (창모) - BLUE MOON (Prod. GroovyRoom) [MP3 Audio]',
    '29. Sunny Side Up!',
    '30. Sweet but Psycho',
    '31. 빌리 아일리시(Billie Eilish) - bad guy / 가사 해석',
    '32. Pastel＊Palettes「もういちど ルミナス」アニメMV（フルサイズver ）',
    '33. PRODUCE 48 (프로듀스 48) - Rumor (루머) Color Coded Han/Rom/Eng Lyrics',
    '34. EXO-K - 3.6.5 (Color Coded Hangul/Rom/Eng Lyrics)',
    "35. EXO-K - Don't Go (나비소녀) (Color Coded Han|Rom|Eng Lyrics)",
    '36. [한글 자막]페르소나 3 ost - 너의 기억 キミの記憶',
    '37. 【合いの手字幕付】ゆりゆららららゆるゆり大事件/Yuriyurarararayuruyuri Daijiken',
    '38. OH MY GIRL (오마이걸) - Dolphin (Color Coded Lyrics Eng/Rom/Han/가사)',
    '39. [M/V] OOHYO (우효) - Brave (Single Cut)',
    '40. Caravan Palace - Moonshine (Album audio)',
    '41. 그대뿐인지 All But You',
    '42. 탄지로의 노래 - 귀멸의 칼날OST 한국어COVER (竈門炭治郎のうた -  鬼滅の刃 OST)',
    '43. Bazzi - Myself (Lyrics)',
    '44. Gia Woods - Feel It',
    '45. [MV] IU(아이유) _ eight(에잇) (Prod.&Feat. SUGA of BTS)',
    '46. IZ*ONE (아이즈원) – Sunflower / Hey. Bae. Like it. (해바라기) Lyrics (Color Coded Han/Rom/Eng)',
    '47. APINK (에이핑크) - %% (Eung Eung(응응)) (Color Coded Lyrics Eng/Rom/Han/가사)',
    '48. 옥탑방이 좋았다면 이걸 들어보세요🦻🏻엔플라잉 띵곡 모음💓',
    '49. 내가 좋아하는 엔플라잉 노래 모음 (기가 막혀 -아 진짜요) |Nflying Playlist (Awesome-Oh really)',
    '50. 키아라 한국어 음성대사 블랙서바이벌 : 영원회귀 / Eternal Return : Black Survival Chiara Korean Voice',
    '51. The XX   Intro HQ',
    '52. Timecop1983 - Lovers (feat. SEAWAVES)',
    '53. Daniel Gunnarsson - All Emotions',
    "54. Daniel Gunnarsson - I'll Never Die",
    '55. Timecop1983 - Tokyo (feat. Kinnie Lane)',
    '56. Breath of a Serpent',
    '57. Heo Young Saeng - Let It Go (Audio)',
    '58. Kim Kyu Jong - Yesterday (부제: 어제보다 슬픈 오늘...) [Han & Eng]',
    '59. [Angelkist 9th] 새벽의 시',
    '60. [Angelkist 7th] 19. Without You',
    '61. twenty one pilots - Regional at Best - Kitchen Sink',
    '62. K/DA - I’LL SHOW YOU ft. TWICE, Bekuh BOOM, Annika Wells (Official Audio)',
    "63. [🌟신곡] 👸여왕의 귀환👸 Who's Laughing Now - Ava Max [가사/해석/가사해석/Lyrics/Kor/Eng]",
    '64. Hades - Lament of Orpheus',
    '65. Hades - Good Riddance (feat. Ashley Barrett)',
    '66. Hades - Good Riddance (Orpheus Only)',
    '67. Hades - Good Riddance (Eurydice Solo feat. Ashley Barrett)',
    '68. K/DA MORE Lyrics / No Seraphine ver. (세라핀 없는 버전 가사)',
    '69. [Angelkist 9th] Once Again',
    '70. [MV] 우효(OOHYO) _ 청춘(Youth) (DAY)',
    `71. "It's Time"- Imagine Dragons (Lulu Antariksa Cover)`,
    '72. The Weeknd - Blinding Lights (Lyrics)',
    '73. Jason Derulo - Savage Love (Lyrics) FT. Jawsh 685',
    '74. WA -- 전진 featuring 주희',
    '75. 가호 (GAHO)_ 시작 START (이태원클라쓰/ITAEWON CLASS OST Part 2) [가사 LYRICS] 한국어',
    '76. Rizky Ayuba - Kimi No Toriko (Lyrics) | Ki minno tori ko ni natte, shimae ba kitto',
    "77. You Know I'll Go Get",
    '78. Silver',
    '79. Coldplay & Big Sean - Miracles (Someone Special) - Official Lyric Video',
    '80. Wrap Me In Plastic - CHROMANCE (Lyrics Video)',
    '81. 문문 결혼 가사',
    '82. Mistress',
    "83. J.Y. Park, SUNMI 'When We Disco' Lyrics (박진영 선미 When We Disco 가사) (Color Coded Lyrics)",
    '84. Young Ejecta • Welcome To Love',
    '85. Young Ejecta - Build A Fire',
    '86. 【Hatsune Miku】Baka Mitai【VOCALOID Cover】[+VSQ]',
    '87. 임재범 (YIM JAE BEUM)－「너를 위해 FOR YOU」 [LYRICS] 가사 한국어',
    '88. 김아중 - 마리아 (Kim Ah Joong - Maria) Lyrics',
    '89. BTS We are Bulletproof : the Eternal Lyrics (방탄소년단) [Color Coded Lyrics/Han/Rom/Eng]',
    '90. BTS Moon Lyrics (방탄소년단 Moon 가사) [Color Coded Lyrics/Han/Rom/Eng]',
    '91. Nell (넬) - 현실의 현실',
    '92. Full Confession',
    '93. 05 살아있는 너의 밤',
    "94. Yorushika - That's Why I Gave Up on Music (MUSIC VIDEO)",
    '95. 마크툽(MAKTUB)-오늘도 빛나는 너에게(To You My Light)(Feat.이라온,반광옥,정영은,전상근) End Game [8K]',
    '96. I Love You',
    '97. [Indie Dance] - LVTHER - Some Kind Of Magic (feat. MYZICA) [Monstercat Release]',
    '98. Sarah McLachlan - U Want Me 2',
    '99. How To Get Away With Murder | IAMX - The Great Shipwreck Of Life',
    '100. (한글 번역) Jack Stauber - Buttercup',
  ];
  const n = 2048;
  const r = reduceDescriptions(o, n);
  expect(r.join("\n").length).toBeLessThanOrEqual(n);
  console.log(r.join("\n"));
  console.log(o.join("\n").length, "=>", r.join("\n").length);
});